name: ci

on:
  push:
    paths-ignore:
      - '**/README.md'
    branches:
      - 'main'
      - 'release-*'
      - 'FE-*'
      - 'BF-*'
      - 'PU-*'
      - 'DOC-*'
      - 'hotfix-*'
    tags:
      - '*' # Push events to matching *, i.e. 1.0.0 v1.0, v20.15.10
  pull_request:
    paths-ignore:
      - '**/README.md'
    types: # https://docs.github.com/actions/using-workflows/events-that-trigger-workflows#pull_request
      - opened
      - reopened
      - closed
    branches:
      - 'main'
      - 'release-*'
      - 'DOC-*'
      - 'hotfix-*'

permissions:
  contents: write
  discussions: write

jobs:
  version:
    name: version
    uses: ./.github/workflows/version.yml

  golang-ci:
    name: golang-ci
    needs:
     - version
    uses: ./.github/workflows/golang-ci.yml
    secrets: inherit

  go-build-check-main:
    name: go-build-check-main
    needs:
     - version
     - golang-ci
    # if: ${{ ( github.event_name == 'push' && github.ref == 'refs/heads/main' ) || github.base_ref == 'main' }}
    uses: ./.github/workflows/go-release-platform.yml
    secrets: inherit
    with:
      version_name: latest
      upload_artifact_name: go-release

  deploy-tag-dry-run:
    needs:
      - version
      - go-build-check-main
    name: deploy-tag-dry-run
    uses: ./.github/workflows/deploy-tag.yml
    secrets: inherit
    with:
      dry_run: true
      prerelease: true
      tag_name: "1.0.1"
      tag_changes: ${{ needs.version.outputs.cc_changes }}
      download_artifact_name: go-release

  docker-image-latest:
    name: docker-image-latest
    needs:
      - version
    uses: ./.github/workflows/docker-image-latest.yml
    if: ${{ ( github.event_name == 'push' && github.ref == 'refs/heads/main' ) || ( github.base_ref == 'main' && github.event.pull_request.merged == true ) }}
    secrets: inherit
    with:
      docker_hub_user: 'woodpecker-kit'
      docker_image_name: 'woodpecker-kit/woodpecker-tools'
      build_branch_name: 'main'
      # push_remote_flag: ${{ github.event.pull_request.merged == true }}
      # push_remote_flag: ${{ github.ref == 'refs/heads/main' }}

  go-release-platform:
    name: go-release-platform
    needs:
     - version
     - golang-ci
    if: startsWith(github.ref, 'refs/tags/')
    uses: ./.github/workflows/go-release-platform.yml
    secrets: inherit
    with:
      version_name: ${{ needs.version.outputs.tag_name }}
      upload_artifact_name: go-release

  docker-image-tag:
    name: docker-image-tag
    needs:
      - version
    uses: ./.github/workflows/docker-image-tag.yml
    if: startsWith(github.ref, 'refs/tags/')
    secrets: inherit
    with:
      push_remote_flag: false
      docker_hub_user: 'woodpecker-kit'
      docker_image_name: 'woodpecker-kit/woodpecker-tools'

  deploy-tag:
    needs:
      - version
      - go-release-platform
      - docker-image-tag
    name: deploy-tag
    uses: ./.github/workflows/deploy-tag.yml
    if: startsWith(github.ref, 'refs/tags/')
    secrets: inherit
    with:
      prerelease: true
      tag_name: ${{ needs.version.outputs.tag_name }}
      tag_changes: ${{ needs.version.outputs.cc_changes }}
      download_artifact_name: go-release